# Stemming, Lemmatizing, WordNet

Ex: Connecting, connection, connect
supaya komputer tau kalo kedua kata pertama itu dibentuk dari kata ketiga

ini bakal sangat efektif untuk ngehemat processing power dan improve result
karena tanpa 3 proses ini, bakal butuh processing power yang berbeda untuk ngeproses 3 kata tersebut, boros

**Stemming**\
cuma motong suku katanya, jadi bisa jadi ada karakter yang hilang
dia bakal bandingin beberapa kata, lalu cari irisan yang sama sebagai hasil, jadi akurasinya jelek

Ex:
- continuing -> continu(ing)
- caresses -> caress(es)

Types of stemmers
1. Porter Stemmer -> hanya bisa di bahasa inggris
2. Snowball Stemmer -> bisa di banyak bahasa, porter 2
3. Lancaster Stemmer -> paling aggresive, paling cepat, tapi hasilnya jelke banget

In [53]:
from nltk.stem import PorterStemmer, SnowballStemmer, LancasterStemmer
import pandas as pd

In [54]:
porter = PorterStemmer()
snowball = SnowballStemmer('english')
lancaster = LancasterStemmer()

In [55]:
words = [
    "studies", "studying", "better", "children", "mice", "running", "happiness", "relational", "organization", "went", "universe", "university"
]

In [56]:
data = []
for word in words:
    data.append({
        "Original": word,
        "Porter": porter.stem(word),
        "Snowball": snowball.stem(word),
        "Lancaster": lancaster.stem(word),
    })
    
df = pd.DataFrame(data)
df

        Original    Porter  Snowball Lancaster
0        studies     studi     studi     study
1       studying     studi     studi     study
2         better    better    better       bet
3       children  children  children    childr
4           mice      mice      mice       mic
5        running       run       run       run
6      happiness     happi     happi     happy
7     relational     relat     relat       rel
8   organization     organ     organ       org
9           went      went      went      went
10      universe   univers   univers   univers
11    university   univers   univers   univers


**Lemmatizing**\
mencari kata dasarnya juga, jadi bakal kepisah dengan lebih baik
bakal akses Lexical database terlebih dahulu menemukan kata asli

Cons: bakal makan waktu lebih lama

In [57]:
from nltk.stem import WordNetLemmatizer

In [58]:
lemmatizer = WordNetLemmatizer()

In [59]:
for word in words:
    print(word, "->", lemmatizer.lemmatize(word))
    

# untuk noun, preposition-nya nggak akan diilangin (makanya masih ada '-ing'nya)

studies -> study
studying -> studying
better -> better
children -> child
mice -> mouse
running -> running
happiness -> happiness
relational -> relational
organization -> organization
went -> went
universe -> universe
university -> university

In [60]:
word = "better"

adverb = lemmatizer.lemmatize(word, "r")
verb = lemmatizer.lemmatize(word, "v")
adjective = lemmatizer.lemmatize(word, "a")
noun = lemmatizer.lemmatize(word)  # by default bakal udah noun, ngga usah diset lagi

print(adverb, verb, adjective, noun)

well better good better

In [61]:
from nltk.tag import pos_tag
from nltk.corpus import wordnet

In [62]:
pos_tags = pos_tag(words)
pos_tags

[('studies', 'NNS'),
 ('studying', 'VBG'),
 ('better', 'RBR'),
 ('children', 'NNS'),
 ('mice', 'RB'),
 ('running', 'VBG'),
 ('happiness', 'JJ'),
 ('relational', 'JJ'),
 ('organization', 'NN'),
 ('went', 'VBD'),
 ('universe', 'JJ'),
 ('university', 'NN')]

In [63]:
def get_pos(tag):
    if tag.startswith("J"):
        return wordnet.ADJ
    elif tag.startswith("R"):
        return wordnet.ADV
    elif tag.startswith("V"):
        return wordnet.VERB
    return wordnet.NOUN

In [64]:
for word, tag in pos_tags:
    print(word, '->', lemmatizer.lemmatize(word, get_pos(tag)))

studies -> study
studying -> study
better -> well
children -> child
mice -> mice
running -> run
happiness -> happiness
relational -> relational
organization -> organization
went -> go
universe -> universe
university -> university

In [65]:
data = []
for word, tag in pos_tags:
    data.append({
        "Original": word,
        "Porter": porter.stem(word),
        "Snowball": snowball.stem(word),
        "Lancaster": lancaster.stem(word),
        "Lemmatizer": lemmatizer.lemmatize(word),
        "Lemmatizer (POS)": lemmatizer.lemmatize(word, get_pos(tag))
    })
    
df = pd.DataFrame(data)
df

        Original    Porter  Snowball Lancaster    Lemmatizer Lemmatizer (POS)
0        studies     studi     studi     study         study            study
1       studying     studi     studi     study      studying            study
2         better    better    better       bet        better             well
3       children  children  children    childr         child            child
4           mice      mice      mice       mic         mouse             mice
5        running       run       run       run       running              run
6      happiness     happi     happi     happy     happiness        happiness
7     relational     relat     relat       rel    relational       relational
8   organization     organ     organ       org  organization     organization
9           went      went      went      went          went               go
10      universe   univers   univers   univers      universe         universe
11    university   univers   univers   univers    university       university

## WordNet
- lexical database untuk bahasa inggris

disimpan dalam bentuk synsets (synonim sets), isinya:
- synonyms
- anonyms
- definition
- hypernym & hyponym\
*ex: cat is an animal (cat is hypernym)*

In [66]:
from nltk.corpus import wordnet

In [67]:
for word in words:
    synonyms = []
    antonyms = []
    
    synsets = wordnet.synsets(word)
    
    for syn in synsets:
        for lemma in syn.lemmas():
            synonyms.append(lemma.name())
            for ant in lemma.antonyms():
                antonyms.append(ant.name())
                
    print(f"Words: {words[:5]}")
    print(f"Synonyms: {synonyms[:5]}")
    print(f"Antonyms: {antonyms[:5]}")
    print("--------------------")

Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['survey', 'study', 'study', 'work', 'report']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['perusal', 'perusing', 'poring_over', 'studying', 'analyze']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['better', 'bettor', 'better', 'wagerer', 'punter']
Antonyms: ['worsen', 'worsen', 'worse', 'worse', 'bad']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['child', 'kid', 'youngster', 'minor', 'shaver']
Antonyms: ['parent']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['mouse', 'shiner', 'black_eye', 'mouse', 'mouse']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['run', 'running', 'running_play', 'running_game', 'run']
Antonyms: ['malfunction', 'idle', 'standing', 'passing', 'standing']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['happiness', 'felicity', 'happiness']
Antonyms: ['unhappiness', 'sadness']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['relational']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['organization', 'organisation', 'arrangement', 'organization', 'organisation']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['travel', 'go', 'move', 'locomote', 'go']
Antonyms: ['stay_in_place', 'come', 'malfunction', 'be_born', 'stop']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['universe', 'existence', 'creation', 'world', 'cosmos']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['university', 'university', 'university']
Antonyms: []
--------------------

In [68]:
import regex
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [69]:
sentence = "The children are playing better games and studying harder!! 😊😂"

sentence = sentence.lower()
sentence = re.sub(r'\W', ' ', sentence)
sentence = re.sub(r'\d', ' ', sentence).strip()

tokens = word_tokenize(sentence)

stop_words = stopwords.words('english')

tokens = [token for token in tokens if token is not stop_words]

# Ini bentuk lain dari yang atas
# data = []
# for token in tokens:
#     if token not in stop_words:
#         data.append(token)

tokens

['the',
 'children',
 'are',
 'playing',
 'better',
 'games',
 'and',
 'studying',
 'harder']

In [72]:
pos_tags = pos_tag(tokens)
lemmatized = [lemmatizer.lemmatize(word, get_pos(tag)) for word, tag in pos_tags]

for word in lemmatized:
    synonyms = []
    antonyms = []
    
    synsets = wordnet.synsets(word)
    
    for syn in synsets:
        for lemma in syn.lemmas():
            synonyms.append(lemma.name())
            for ant in lemma.antonyms():
                antonyms.append(ant.name())
                
    print(f"Words: {words[:5]}")
    print(f"Synonyms: {synonyms[:5]}")
    print(f"Antonyms: {antonyms[:5]}")
    print("--------------------")

Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: []
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['child', 'kid', 'youngster', 'minor', 'shaver']
Antonyms: ['parent']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['beryllium', 'Be', 'glucinium', 'atomic_number_4', 'be']
Antonyms: ['differ']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['play', 'drama', 'dramatic_play', 'play', 'play']
Antonyms: ['tightness']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['good', 'good', 'goodness', 'good', 'goodness']
Antonyms: ['evil', 'evilness', 'bad', 'badness', 'bad']
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['game', 'game', 'game', 'game', 'game']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: []
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['survey', 'study', 'study', 'work', 'report']
Antonyms: []
--------------------
Words: ['studies', 'studying', 'better', 'children', 'mice']
Synonyms: ['difficult', 'hard', 'hard', 'hard', 'hard']
Antonyms: ['easy', 'soft', 'soft', 'voiced', 'soft']
--------------------